Add navigation to the Awesome book project
Tobinchilongo/Awesome-Books pull request #3
Opened 2022-01-04 15:31 UTC by tariktesfa

In this PR, we added contact information and implemented navigation for displaying 

- List of books
- Add a new book and 
- Contact information

And in this PR the following files are included:-

- index.html to add the HTML contents
- style.css to give styling to the page
- main.js to add the script to the page and 
- linter files to check the linter errors

2022-01-04 17:16 UTC, arslanbisharat requested changes
# Changes Requested, 

Hi there, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have limited number of code reviews per project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```

2022-01-04 17:16 UTC, arslanbisharat commented on index.html
> +      <h1><a href="#">Awesome Books</a></h1>
- [ ] You have a Readme but please add a descriptive readme in your project.

2022-01-04 17:16 UTC, arslanbisharat commented on index.html
> +        <li><a href="#" class="nav-item-2">Add New</a></li>
- [ ] [Optional] Add a live demo link of your app in your project readme.

2022-01-04 17:16 UTC, arslanbisharat commented on main.js
> +  // const date = currentDate.toLocaleString(luxon.DateTime.DATETIME_MED_WITH_SECONDS);
- [ ]  Remove commented code from your project. This makes code hard to read.

2022-01-04 20:11 UTC, andersonlebon requested changes
### Hi @Tobinchilongo

Great work on making the changes requested by the previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![almost-there](https://user-images.githubusercontent.com/65068771/141811112-252360b9-757f-4279-bb3b-b7a2a4675ad3.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
## Required Changes ♻️

- [ ] Kindly check comments under the review.

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-04 20:11 UTC, andersonlebon commented on main.js
> +  // const date = currentDate.toLocaleString(luxon.DateTime.DATETIME_MED_WITH_SECONDS);
- [x] Kindly remove the commented code as the previous reviewer recommended. This will make your code clear and maintainable.
- [x] Currently, your readme only contains a heading but according to the requirements, this file should contain all necessary information. kindly let's use microverse `readme` template for this implementation.

2022-01-05 06:18 UTC, andersonlebon approved these changes
Hi @Tobinchilongo 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 :clap: :clap: :100: 

![nodding-yes](https://user-images.githubusercontent.com/65068771/143095390-344d1cb0-b853-4b91-8662-5d9049dc9e60.gif)

## To highlight :champagne: 
- All linters are passing :heavy_check_mark: 
- Good commit history :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Your README file is now professional :heavy_check_mark: 

## Optional suggestions
- [ ] Kindly Check the comments under the review._
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2022-01-05 06:23 UTC, merged